const tempData = [
  {
    _id: "60e87293c166800e35adb0f2",
    name: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Beatae, laboriosam!",
    type: "issue",
    addedBy: "aldrinjenson",
    addedGroupId: "-408110969",
    addedDate: "1625846400",
    addedGroupName: "Sub group Q",
    assignee: null,
    criticalDate: new Date(),
    mainGroupId: "-507658471",
    isOpen: true,
    recordId: "SG/I-1",
    impact: "High",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "60f065d9581b823c72808ed6",
    name: "Lorem ipsum dolor sit amet",
    type: "issue",
    addedBy: "aldrinjenson",
    addedGroupId: "-408110969",
    addedDate: "1626367402",
    addedGroupName: "Sub group Q",
    assignee: null,
    criticalDate: new Date(),
    mainGroupId: "-507658471",
    isOpen: true,
    recordId: "SG/I-2",
    impact: "Low",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "60f06602581b823c72808edb",
    name: "consectetur adipisicing elit. Quo tempore consectetur quos ",
    type: "issue",
    addedBy: "aldrinjenson",
    addedGroupId: "-408110969",
    addedDate: "1626367453",
    addedGroupName: "Sub group Q",
    assignee: "Johnny Doe",
    criticalDate: new Date(),
    mainGroupId: "-507658471",
    isOpen: true,
    recordId: "SG/I-3",
    impact: "Medium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "60f06645581b823c72808ee0",
    name: "voluptates excepturi cumque ad obcaecati unde totam? Voluptas reprehenderit, earum repellat asperiores harum numquam. Placeat maxime et possimus!",
    type: "issue",
    addedBy: "aldrinjenson",
    addedGroupId: "-408110969",
    addedDate: "1626367500",
    addedGroupName: "Sub group Q",
    assignee: "Jane Doe",
    criticalDate: null,
    mainGroupId: "-507658471",
    isOpen: true,
    recordId: "SG/I-4",
    impact: "High",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "60f06645581b823c72808ee0",
    name: "Test issue 4",
    type: "issue",
    addedBy: "anithesin",
    addedGroupId: "-408110969",
    addedDate: "1626367500",
    addedGroupName: "Site V",
    assignee: null,
    criticalDate: null,
    mainGroupId: "-507658471",
    isOpen: true,
    recordId: "SV/I-9",
    impact: "High",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "60f06645581b823c72808ee0",
    name: "Test issue",
    type: "issue",
    addedBy: "aldrinjenson",
    addedGroupId: "-408110969",
    addedDate: "1626367500",
    addedGroupName: "Random Group",
    assignee: "Jason Vithayahathil",
    criticalDate: new Date(),
    mainGroupId: "-507658471",
    isOpen: true,
    recordId: "RG/I-7",
    impact: "High",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const tempMessage = {
  message_id: 1878,
  from: {
    id: 945086573,
    is_bot: false,
    first_name: "Aldrin",
    last_name: "Jenson",
    username: "aldrinjenson",
    language_code: "en",
  },
  chat: {
    id: -408110969,
    title: "Main Group 1",
    type: "group",
    all_members_are_administrators: true,
  },
  date: 1626425523,
  text: "/issue@issue_and_risk_logger_bot",
  entities: [{ offset: 0, length: 32, type: "bot_command" }],
};
module.exports = { tempData, tempMessage };
